name: Build and Push Images

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push api
        uses: docker/build-push-action@v4
        with:
          context: .
          file: services/api/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/api:latest
      - name: Build and push bot
        uses: docker/build-push-action@v4
        with:
          context: .
          file: services/bot/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/bot:latest
      - name: Build and push worker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: services/worker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/worker:latest
